name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Create image
      id: create_image  
      uses: ./
      with:
        hcti_user_id: ${{ secrets.HCTI_USER_ID }}
        hcti_api_key: ${{ secrets.HCTI_API_KEY }}
        html: '<div class="box">Hello, world</div>'
        css: '.box { width: 400px }'   
    - name: Print url  
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: ${{ steps.create_image.outputs.url }}
